[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'zivyangll/git-blame.vim'

[[plugins]]
repo = 'yianwillis/vimcdoc'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'drmingdrmer/xptemplate'

[[plugins]]
repo = 'tell-k/vim-autopep8'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'tacahiroy/ctrlp-funky'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'morhetz/gruvbox'
